# Generated by Django 3.1.5 on 2021-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_completedorder_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='product',
        ),
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
