# Generated by Django 3.1.5 on 2021-03-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ordered_items',
        ),
    ]
